spring:
  datasource:
    url: jdbc:mysql://devdb.ubuilder.co.kr:3306/frd?characterEncoding=UTF-8&serverTimezone=UTC
    username: frdsample
    password: accurafrd@a1!
    hikari:
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
logging:
  file:
    name: log/inventory.log
    max-size: 10MB
    max-history: 1000